site_name: Emdros Programmer's Reference Guide
site_url: https://progref.emdros.com/
site_description: Programmer's Reference Guide for the Emdros text database engine
site_author: Ulrik Sandborg-Petersen

   
theme: readthedocs

pages:
    - Home: index.md
    - Installing Emdros:
         - Home: installing/index.md
         - Linux: installing/linux.md
         - Mac: installing/mac.md
         - Windows: installing/windows.md
    - Calling Emdros:
         - Ways to call Emdros: calling_emdros/index.md
         - CLI: calling_emdros/cli.md
         - C++ SDK: calling_emdros/sdk.md
         - SWIG: calling_emdros/swig.md
         - Web API: calling_emdros/webapi.md
         - iOS: calling_emdros/ios.md
         - Android: calling_emdros/android.md
    - Harvest Library:
         - What is it?: harvestlib/index.md
         - Render Library: harvestlib/renderlib.md
         - FTS Library: harvestlib/ftslib.md
    - About:
         - Release Notes: about/release-notes.md
         - Contributing: about/contributing.md
         - License: about/license.md

copyright: Copyright &copy; 2019 <a href="https://emdros.org/">Sandborg-Petersen Holding ApS</a>.
#google_analytics: ['UA-XXX', 'progref.emdros.com']
